server:
  port: ${SEVER_PORT:8080}

spring:
  datasource:
    url: ${H2_URL}
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}
    driver-class-name: ${H2_DRIVER}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database-platform: ${H2_DIALECT}
  h2:
    console:
      enabled: true
      path: /h2-console


logging:
  level:
    root: ${INFO}
    io.github.sunday: ${APP_LOG_LEVEL_DEV}
    org.springframework:
      security: ${APP_LOG_LEVEL_DEV}
      securityoauth2: ${APP_LOG_LEVEL_DEV}
