server:
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: DevFolio
  servlet:
    multipart:
      enabled: true
      max-file-size: ${MAX_FILE_SIZE:5MB}
      max-request-size: ${MAX_REQUEST_SIZE:5MB}
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  mail:
    host: smtp.gmail.com
    port: 587
    username: est.devfolio@gmail.com
    password: jrtqmmkwncdknsxc
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

app:
  name: ${APP_NAME:DevFolio}
  version: ${APP_VERSION:0.0.0}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    io.github.sunday: ${APP_LOG_LEVEL:INFO}