server:
  error:
    whitelabel:
      enabled: false

spring:
  profiles:
    active: production
  application:
    name: DevFolio
  servlet:
    multipart:
      enabled: true
      max-file-size: ${MAX_FILE_SIZE:100MB}
      max-request-size: ${MAX_REQUEST_SIZE:100MB}
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: ${MAIL_SMTP_AUTH}
      mail.smtp.starttls.enable: ${MAIL_SMTP_STARTTLS_ENABLE}

app:
  name: ${APP_NAME:DevFolio}
  version: ${APP_VERSION:0.0.0}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    io.github.sunday: ${APP_LOG_LEVEL:INFO}