server:
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: DevFolio
  servlet:
    multipart:
      enabled: true
      max-file-size: ${MAX_FILE_SIZE:5MB}
      max-request-size: ${MAX_REQUEST_SIZE:5MB}
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: ${MAIL_SMTP_AUTH}
      mail.smtp.starttls.enable: ${MAIL_SMTP_STARTTLS_ENABLE}

app:
  jwt:
    issuer: DevFolio
    access-ttl-ms: 1800000  # 30m
    refresh-ttl-ms: 1209600000 # 14d
    secret: ${JWT_SECRET}     # HS256 서명키 (32바이트 이상 권장)
    refresh-pepper: ${REFRESH_TOKEN_PEPPER} # RT 해시용 HMAC 키
  name: ${APP_NAME:DevFolio}
  version: ${APP_VERSION:0.0.0}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    io.github.sunday: ${APP_LOG_LEVEL:INFO}